name: Go Test on Push

on:
  push:
    branches:
      - L2B

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.20.3'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Go Test
        working-directory: ./src/raft
        run: go test -run 2B
